<a href="https://colab.research.google.com/github/iammras/Machine-Learning-/blob/main/Numpy/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing numpy and giving it a name np
import numpy as np

📐 Creating Arrays

In [ ]:
#1D array

a=np.array([1,2,3,4,5],dtype="int32")

In [ ]:
#2d array

b=np.array([[1,2,3],[4,5,6],[7,8,9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3d array is a collection of 2D arrays
#structure:-(depth,row, column) where depth is number of 2d matrices
c=np.array([[[1,2],[3,1]]])

[[[1 2]
  [3 1]]]



🧪 Array Attributes

In [ ]:
# shape:- which tells you how many number of rows and cols does an array consists of
a.shape

#ndim:- tells you how many dimensions and array consists
b.ndim

# dtype:- for checking the data types of an array
c.dtype

# size:- for total number of elements in an array
c.size

#itemsize:- size of each item in bytes
a.itemsize

4


🧱 Array Creation Functions

In [ ]:
# All zeros
np.zeros((5,5))

#All ones
np.ones((7,7))

#All 5s
np.full((7,7),5)

#identity matrix
np.eye(7)

#arange(start,stop,step)
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


🧮 Indexing & Slicing

In [122]:
# first row
a[0]

#element at second row third column
b[1][2]


""""
row slicing
arr[start_row:end_row]
"""
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0:1])

"""
coloumn slicing
arr[:, start_col:end_col]

"""
print(arr[:,1:2])

"""
arr[row_start:row_end, col_start:col_end]
for both the row and the cols slicing

"""
print(arr[0:2,1:3])


[[10 20 30]]
[[20]
 [50]
 [80]]
[[20 30]
 [50 60]]


🔄 Array Operations

In [61]:
#element wise
arr=np.ones(4,dtype="int32")
brr=np.ones(4)
print(arr+brr)
print(arr-brr)
print(arr*brr)
print(arr/brr)

#dot product
print(np.dot(arr,brr))

#for adding 5 to each element of the array arr
print(arr+5)

[2. 2. 2. 2.]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
4.0
[6 6 6 6]


**🎯 Useful NumPy Fuction**

In [68]:
print(np.sum(arr)) # return the sum of the array
print(np.min(arr)) # return the minimum element of the array
print(np.max(arr)) # return the maximum element of the array
print(np.mean(arr)) # return the mean of the array
print(np.sqrt(arr)) #  Returns the square root of each element
print(np.exp(arr)) #Calculates the exponential (e^x) for each element in the array.e is Euler’s number ≈ 2.718
print(np.argmax(arr)) # return the index of the minimum element in the array
print(np.argmin(arr)) # return the index of the maximum element in the array

4
1
1
1.0
[1. 1. 1. 1.]
[2.71828183 2.71828183 2.71828183 2.71828183]
0
0


**🎲 Random Number Generation**

In [86]:
arr=np.random.rand(5,8) #random decimal values between 0 and 1
arr=np.random.randint(1,10,(5,8)) # random integer values between 1 and 10(exlusive)
arr=np.random.randn(5,8) # random decimal values following a standard normal distribution and having a mean=0
print(arr)

[[ 1.3460366  -0.31716755 -0.09160339  1.3717608   1.09742378  1.98839709
   0.53328266 -1.03559186]
 [ 2.5008126   1.19650038  2.49331604  1.46363837  0.13221862  0.73643522
   0.62339944 -0.18536927]
 [-1.92830628 -0.10540516  0.58481659 -0.80036176  0.81644302  0.90980925
   0.98960833  0.31376667]
 [ 0.51197333  0.78374822 -1.72995231 -1.11147747  0.58390572  1.53225675
   1.35069584  0.42347269]
 [ 2.00075766 -0.53139432  0.71037521  1.81964673 -0.36171901 -0.55620706
   0.02974104  0.70008411]]


**🧪 Boolean Masking & Filtering**

In [95]:
arr=np.array(np.full(5,5))
arr[2]=4
arr[3]=1
print(arr==5) # This compares every element in the array with 5 and returns a Boolean array (True or False):
print(arr[arr<5]) # "Give me only the elements where the condition arr > 5 is True."

[ True  True False False  True]
[4 1]


**🛠️ Array Sorting & Unique**

In [98]:
arr=[5,4,1,9,9,78]
print(np.sort(arr)) # return the sorted array

print(np.unique(arr)) # it returns the unique element of the array as a set data structure

[ 1  4  5  9  9 78]
[ 1  4  5  9 78]


**🧹 Copy vs View**

In [100]:
arr=np.array([1,3,5,6,6,6,7,8,9])
brr=arr.copy() #independent copy Creates a new array in a new memory location.Any changes to brr won’t affect arr.
crr=arr.view() #Creates a shallow copy that shares the same data as arr.Changes to the data in crr will affect arr, and vice versa.
print(crr)
print(brr)
print(arr)

[1 3 5 6 6 6 7 8 9]
[1 3 5 6 6 6 7 8 9]
[1 3 5 6 6 6 7 8 9]


**🧭 Axis Explanation**

In [107]:
arr=np.full((5,3),5)
print(arr)
print(np.sum(arr,axis=0)) # when axis=0 it calculate  → Operates column-wise (down) for each coloumn and return the array
print(np.mean(arr,axis=1)) # when axis=1 it calculate -> operates row-wise(across) for each row it do operation and then return an array


[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[25 25 25]
[5. 5. 5. 5. 5.]


**🧊 Stacking Arrays**

In [109]:
arr=np.array([1,3,4,5])
brr=np.array([4,5,6,6])
crr=np.vstack([arr,brr])#Stacks arrays on top of each other (like rows in a table).Resulting array has more rows.
print(crr)
drr=np.hstack([arr,brr])# Stacks arrays side by side (like extending columns).Resulting array has more columns.
print(drr)
"""
⚠️ Important Notes:
Both arrays must have the same number of columns for vstack

Same number of rows for hstack (if 2D)
"""

[[1 3 4 5]
 [4 5 6 6]]
[1 3 4 5 4 5 6 6]


**🔁 Reshape, Flatten & Resize**

In [114]:
"""
 reshape() – Create a Reshaped View (without changing original)
Returns a new array with the shape you specify.

The original array remains unchanged.

Number of elements must match.
"""
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
"""
🧲 flatten() – Convert to 1D (returns a copy)
🔹 What it does:
Converts any multidimensional array into 1D.

Returns a new array (not a view).

Original array is not changed

"""
arr=np.array([[1,2,3],[3,4,5]])
print(arr.flatten())

""""
🔧 resize() – Change shape in-place (modifies original)
🔹 What it does:
Changes the shape of the array in-place.

The original array is modified directly.

If needed, it fills extra space with zeros (or junk data).

Not commonly used in ML; use reshape() instead.


"""
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 3 4 5]
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]
