<a href="https://colab.research.google.com/github/iammras/Machine-Learning-/blob/main/Numpy/NumPy_Practice_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1:-Create a 1D array of integers from 10 to 50 (inclusive) with a step of 5.

In [2]:
import numpy as np
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


Q2:- Create a 3x3 array filled with the number 7.

In [3]:
import numpy as np
arr=np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Q3:- Create an array with 10 random integers between 1 and 100.
Find the min, max, and mean of that array.

In [10]:
import numpy as np
arr=np.random.randint(1,100,10)
print(arr)

[95 28  5 31 83 24 33 37 34 64]


Q4:- Create the array arr = np.array([10, 20, 30, 40, 50]) Print the last 3 elements using slicing.

In [13]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-1:-4:-1])
print(arr[2:])

[50 40 30]
[30 40 50]
